# Site settings
title: uGeek
description: "Podcast de Tecnología en el que hablo de GNU/Linux, Raspberry Pi, servidores y tecnología en general"
url: "https://ugeek.github.io"
author:
  name: "Angel"
  email: "ugeekpodcast@gmail.com"
url: "https://ugeek.github.io"

# Build settings
baseurl: '/' # Change this to your relative path (ex: /blog/), or leave just a /
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

#Google Analitics
google_analytics: UA-96879567-1

# Podcast Feed Settings
podcast_url: https://ugeek.github.io
podcast_album_art: https://ugeek.github.io/img/ugeek.png
podcast_title: uGeek
podcast_owner: Angel
podcast_email: ugeekpodcast@gmail.com
podcast_category: Technology
podcast_subcategory_one: Linux
podcast_subcategory_two: Gadgets
podcast_explicit: "no"
podcast_author: Angel
podcast_description: Podcast de Tecnología en el que hablo de GNU/Linux, Raspberry Pi, servidores y tecnología en general.
podcast_summary: Podcast de Tecnología en el que hablo de GNU/Linux, Raspberry Pi, servidores y tecnología en general.
podcast_subtitle: : Podcast de Tecnología en el que hablo de GNU/Linux, Raspberry Pi, servidores y tecnología en general.


# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: true
reverse: false


excerpt_separator: <!--more-->
